import { useState } from "react";
import type { CommercialSignal } from "@workspace/api-client-react";
import { useMarketDashboard } from "@/hooks/use-market-dashboard";
import { MARKET_TIMEFRAMES, formatNumber, formatTimestamp, isMarketTimeframe, type MarketTimeframe } from "@/lib/market";

type Props = { onAccount?: () => void; onAdmin?: () => void; onLogout?: () => void };

export function MarketDashboard({ onAccount, onAdmin, onLogout }: Props) {
  const [timeframe, setTimeframe] = useState<MarketTimeframe>("15m");
  const [historyLimit, setHistoryLimit] = useState(5);
  const { health, dashboard } = useMarketDashboard(timeframe);
  const data = dashboard.data;
  return <main className="min-h-screen overflow-x-hidden bg-[#070812] text-slate-100">
    <div className="mx-auto max-w-6xl px-4 py-5 sm:px-6 lg:px-8">
      <header className="flex flex-col gap-4 rounded-2xl border border-white/8 bg-[#0b0d1b] p-4 sm:flex-row sm:items-center sm:justify-between">
        <div><p className="text-sm font-bold tracking-[0.16em]">NEXO DIGITAL PRO</p><p className="mt-1 text-xs text-slate-500">Señales de mercado</p></div>
        <nav className="flex flex-wrap gap-2" aria-label="Navegación principal"><span className="min-h-11 rounded-lg bg-violet-400/15 px-3 py-3 text-sm font-semibold text-violet-100">Señales</span>{onAccount ? <button className="min-h-11 rounded-lg px-3 text-sm text-slate-300" onClick={onAccount}>Cuenta</button> : null}{onAdmin ? <button className="min-h-11 rounded-lg px-3 text-sm text-violet-200" onClick={onAdmin}>Admin</button> : null}{onLogout ? <button className="min-h-11 rounded-lg border border-white/10 px-3 text-sm" onClick={onLogout}>Cerrar sesión</button> : null}</nav>
      </header>
      <section className="mt-6 flex flex-col gap-4 rounded-2xl border border-white/8 bg-slate-950/55 p-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-200">Producción comercial V1</p><h1 className="mt-2 text-3xl font-semibold">Dashboard de señales</h1><p className="mt-2 text-sm text-slate-400">BTCUSDT activo · XAUUSD 🔒 Próximamente</p></div><label className="grid gap-2 text-sm text-slate-300">Timeframe<select className="min-h-12 rounded-xl border border-white/10 bg-[#090c18] px-4 text-base" value={timeframe} onChange={(event) => isMarketTimeframe(event.target.value) && setTimeframe(event.target.value)}>{MARKET_TIMEFRAMES.map((value) => <option key={value}>{value}</option>)}</select></label></section>
      {dashboard.isPending ? <StateCard title="Actualizando señales" detail="Estamos evaluando la configuración técnica disponible." /> : null}
      {dashboard.isError ? <StateCard error title="No se pudo actualizar" detail="Reintentá en unos instantes. No se mostrará una señal sin datos válidos." action={() => void dashboard.refetch()} /> : null}
      {data ? <><CurrentSignal signal={data.activeSignal} /><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5" aria-label="Resumen de rendimiento"><Metric label="Señales cerradas" value={String(data.metrics.total)} empty={!data.metrics.total} /><Metric label="Ganadas" value={String(data.metrics.wins)} empty={!data.metrics.total} /><Metric label="Perdidas" value={String(data.metrics.losses)} empty={!data.metrics.total} /><Metric label="Win / Loss rate" value={data.metrics.winRate === null ? "—" : `${formatNumber(data.metrics.winRate)}% / ${formatNumber(data.metrics.lossRate)}%`} empty={data.metrics.winRate === null} /><Metric label="Retorno acumulado" value={data.metrics.accumulatedReturnPct === null ? "—" : `${signed(data.metrics.accumulatedReturnPct)}%`} empty={data.metrics.accumulatedReturnPct === null} /></section><section className="mt-6 grid gap-6 lg:grid-cols-[0.65fr_1.35fr]"><article className="rounded-2xl border border-white/8 bg-slate-950/55 p-5"><p className="text-xs font-bold uppercase tracking-[0.15em] text-violet-200">Contexto simplificado</p><dl className="mt-5 space-y-4"><Context label="Tendencia" value={trend(data.context.trend)} /><Context label="Condición" value={condition(data.context.condition)} /><Context label="Fuerza" value={strength(data.context.strength)} /></dl></article><article className="min-w-0 rounded-2xl border border-white/8 bg-slate-950/55 p-5"><p className="text-xs font-bold uppercase tracking-[0.15em] text-violet-200">Registro real</p><h2 className="mt-1 text-xl font-semibold">Historial de señales</h2>{data.history.length ? <div className="mt-5 space-y-3">{data.history.slice(0, historyLimit).map((signal) => <HistoryRow key={signal.id} signal={signal} />)}{historyLimit < data.history.length ? <button className="min-h-11 w-full rounded-xl border border-white/10 text-sm font-semibold" onClick={() => setHistoryLimit((value) => value + 5)}>Ver más historial</button> : null}</div> : <p className="mt-5 rounded-xl border border-white/8 p-4 text-sm text-slate-400">Aún no hay historial real de señales cerradas.</p>}</article></section></> : null}
      <footer className="mt-8 border-t border-white/8 py-6 text-center text-xs text-slate-500">Las señales informan movimiento técnico porcentual. No representan P&amp;L personal ni constituyen asesoramiento financiero. Sistema {health.isSuccess ? "conectado" : "en verificación"}.</footer>
    </div>
  </main>;
}

function CurrentSignal({ signal }: { signal: CommercialSignal | null }) { if (!signal) return <section className="mt-6 rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 to-[#0a0c18] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Señal actual</p><h2 className="mt-4 text-3xl font-semibold">SIN SEÑAL ACTIVA</h2><p className="mt-3 text-slate-400">El sistema está esperando una configuración técnica válida.</p></section>; const long = signal.direction === "LONG"; return <section className={`mt-6 rounded-3xl border p-6 sm:p-8 ${long ? "border-emerald-300/25 bg-emerald-400/[0.06]" : "border-rose-300/25 bg-rose-400/[0.06]"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Señal actual</p><h2 className={`mt-3 text-4xl font-bold ${long ? "text-emerald-300" : "text-rose-300"}`}>{signal.direction}</h2><p className="mt-2 text-lg font-semibold">{signal.symbol} · {signal.timeframe}</p></div><span className="rounded-full border border-white/12 px-3 py-1.5 text-xs font-bold">{signal.status}</span></div><dl className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Context label="Entrada" value={price(signal.entryPrice)} /><Context label="Stop loss" value={price(signal.stopLoss)} /><Context label="Take profit" value={price(signal.takeProfit)} /><Context label="R:R" value={`1:${formatNumber(Number(signal.riskRewardRatio), { maximumFractionDigits: 2 })}`} /></dl><p className="mt-5 text-xs text-slate-500">Abierta: {formatTimestamp(signal.openedAt)}</p></section>; }
function HistoryRow({ signal }: { signal: CommercialSignal }) { return <div className="grid min-w-0 gap-2 rounded-xl border border-white/8 bg-[#090c18] p-4 sm:grid-cols-[1.2fr_0.8fr_0.7fr_0.7fr] sm:items-center"><div><p className="font-semibold">{signal.symbol} · {signal.timeframe}</p><p className="mt-1 text-xs text-slate-500">{formatTimestamp(signal.openedAt)}</p></div><p className={signal.direction === "LONG" ? "text-emerald-300" : "text-rose-300"}>{signal.direction}</p><p className="text-sm">{signal.status}</p><p className={`text-sm font-semibold ${Number(signal.returnPct) >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{signal.returnPct === null ? "—" : `${signed(Number(signal.returnPct))}%`}</p></div>; }
function Metric({ label, value, empty }: { label: string; value: string; empty: boolean }) { return <article className="rounded-2xl border border-white/8 bg-slate-950/55 p-4"><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p>{empty ? <p className="mt-2 text-xs leading-5 text-slate-500">Aún no hay suficiente historial para calcular esta métrica.</p> : null}</article>; }
function Context({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/8 bg-[#090c18] p-3"><dt className="text-[11px] uppercase tracking-[0.12em] text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
function StateCard({ title, detail, error, action }: { title: string; detail: string; error?: boolean; action?: () => void }) { return <section className={`mt-6 rounded-2xl border p-6 ${error ? "border-rose-300/20 bg-rose-400/[0.05]" : "border-white/8 bg-slate-950/55"}`}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 text-sm text-slate-400">{detail}</p>{action ? <button className="mt-4 min-h-11 rounded-xl border border-white/12 px-4" onClick={action}>Reintentar</button> : null}</section>; }
function trend(value: string | null) { return value === "bullish" ? "Alcista" : value === "bearish" ? "Bajista" : value === "sideways" ? "Lateral" : "No disponible"; }
function condition(value: string) { return value === "trending" ? "Mercado en tendencia" : value === "mixed" ? "Mercado mixto" : "Datos insuficientes"; }
function strength(value: string) { return value === "high" ? "Alta" : value === "medium" ? "Media" : "Baja"; }
function price(value: string) { return formatNumber(Number(value), { style: "currency", currency: "USD", maximumFractionDigits: 2 }); }
function signed(value: number) { return `${value > 0 ? "+" : ""}${formatNumber(value, { maximumFractionDigits: 4 })}`; }
